tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_mess_detector: true
    php_changetracking: true
    php_code_sniffer: true
    php_cs_fixer:
        config: { level: all }
    sensiolabs_security_checker: true
    external_code_coverage: true

filter:
    paths: [src/*]
    excluded_paths: [vendor/*, tests/*]
